// CServer.idl : ComServer.dllのIDLソース
//

// このファイルはMIDLツールによって処理され、タイプライブラリ(ComServer.tlb)とマーシャリングコードを生成

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(295D9570-C579-4696-8BE2-C069DEC06F36),
		dual,
		helpstring("ISumUp Interface"),
		pointer_default(unique)
	]
	interface ISumUp : IDispatch
	{
		[id(1), helpstring("method SumUp")] HRESULT SumUp(int a,int b);
	};

[
	uuid(40EAC38A-60AA-4F14-BC5D-C7C3C8DE89C5),
	version(1.0),
	helpstring("ComServer 1.0 Type Library")
]
library CONNECTIONCOMLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(AFE854B0-246F-4B66-B26F-A1060225C71C),
		helpstring("_ISumUpEvents Interface")
	] 
	interface _ISumUpEvents : IUnknown
	{
		[id(1), helpstring("method ExecutionOver")] HRESULT ExecutionOver(int Result);
	};

	[
		uuid(630B3CD3-DDB1-43CE-AD2F-4F57DC54D5D0),
		helpstring("SumUp Class")
	]
	coclass SumUp
	{
		[default] interface ISumUp;
		[default, source] interface _ISumUpEvents;
	};
};